spring.application.name=User-Service
server.port=8484
spring.datasource.url=jdbc:postgresql://localhost:5432/BookMyShow
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.jpa.hibernate.ddl-auto=update